# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
      development
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get Version Number
        uses: nyaayaya/package-version@v1
        with:
          path: 'package.json'
          follow-symlinks: false

      - name: Setup Geckodriver
        uses: browser-actions/setup-geckodriver@latest

      - name: Install node dependencies
        run: npm i

      - name: Run test script in package.json
        run: npm test

      - name: Upload the test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: nightwatch-test-results-${{ env.PACKAGE_VERSION }}-${{ github.run_number }}
          path: tests_output\nightwatch-html-report
